version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "iRedlofSmartHome"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n7sk2xxk6y7o"
s3_prefix = "iRedlofSmartHome"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
